name: Build Plugin

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Show Gradle Version
        run: ./gradlew --version

      - name: Build (no tests)
        run: ./gradlew clean build -x test

      - name: Upload Build Artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: smpCurrency-jars
          path: build/libs/*.jar
          if-no-files-found: error

      - name: Publish Release (tag builds)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Optional: quick gradle dependency cache warm-up (can be removed if not needed)
  dependency-analysis:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Gradle Dependencies
        run: ./gradlew dependencies --configuration compileClasspath || true

